In [17]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np

np.random.seed(0)

In [18]:
#Loading data

df = pd.read_csv('/content/iris_no_label.csv')


In [19]:
df.head()

sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [20]:
df['species'] = pd.Categorical.from_codes(iris.target,
iris.target_names)

df.head()

sepal.length  sepal.width  petal.length  petal.width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [21]:
df['is_train'] = np.random.uniform(0,1 ,len(df)) <= .75
df.head()

sepal.length  sepal.width  petal.length  petal.width species  is_train
0           5.1          3.5           1.4          0.2  setosa      True
1           4.9          3.0           1.4          0.2  setosa      True
2           4.7          3.2           1.3          0.2  setosa      True
3           4.6          3.1           1.5          0.2  setosa      True
4           5.0          3.6           1.4          0.2  setosa      True

In [22]:
train , test = df[df['is_train']== True], df[df['is_train']== False]

print('Number of oobservations in the training data:' ,len(train))
print('Number of oobservations in the test data:' ,len(test))

Number of oobservations in the training data: 118
Number of oobservations in the test data: 32


In [23]:
features = df.columns[:4]

features

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width'], dtype='object')

In [24]:
y = pd.factorize(train['species'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [25]:
clf = RandomForestClassifier(n_jobs=2,random_state=0)
clf.fit(train[features],y)

RandomForestClassifier(n_jobs=2, random_state=0)

In [26]:
# Applying the trained classifier to the test
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [27]:
#View the predicted probabilities of the first 10 observation
clf.predict_proba(test[features])[10:20]

array([[1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.67, 0.33],
       [0.  , 1.  , 0.  ],
       [0.  , 0.82, 0.18],
       [0.  , 0.03, 0.97],
       [0.  , 0.42, 0.58],
       [0.  , 0.99, 0.01],
       [0.  , 0.96, 0.04]])

In [28]:
# mapping name for the plants for each predicted plant class
preds = iris.target_names[clf.predict(test[features])]

#View the PREDICATED species for the first five observations
preds[0:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [29]:
#Viewing the ACTUAL species for the first five observations
test['species'].head()

7     setosa
8     setosa
10    setosa
13    setosa
17    setosa
Name: species, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [30]:
#Creating confusion matrix
pd.crosstab(test['species'], preds, rownames=['Actual Species'],
colnames=['Predicated Species'])

Predicated Species  setosa  versicolor  virginica
Actual Species                                   
setosa                  13           0          0
versicolor               0           5          2
virginica                0           0         12

In [31]:
preds = iris.target_names[clf.predict([[5.0,3.6,1.4,2.0],[5.0,3.6,1.4,2.0]])]
preds

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"


array(['setosa', 'setosa'], dtype='<U10')